# Generated by Django 4.2.13 on 2024-06-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='naveModel',
            fields=[
                ('id_nave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nave', models.CharField(blank=True, default='', max_length=20)),
                ('modelo_nave', models.CharField(blank=True, default='', max_length=20)),
                ('coste_creditos_nave', models.IntegerField(blank=True, default=0)),
                ('num_pasajeros_nave', models.IntegerField(blank=True, default=1)),
            ],
        ),
    ]
